version: 2
updates:
  # Enable version updates for Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    target-branch: "develop"
    reviewers:
      - "andreycpu"
    assignees:
      - "andreycpu"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
    open-pull-requests-limit: 5
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday" 
      time: "06:00"
    target-branch: "develop"
    reviewers:
      - "andreycpu"
    assignees:
      - "andreycpu"
    commit-message:
      prefix: "ci"
    open-pull-requests-limit: 2